### ISSUE TITLE
time resolution in .csv created by vak prep is inacurate

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#104]
when fed with matlab spectrograms vak prep creates a .csv file that contains inaccurate timebin resolution. in this case, the actual time bin is 2.7msec and the .csv file had it as 3msec.

if this timebin resolution is used to calculate time shifts and positions in the input data it may lead to errors

**Comment by NickleDave** [comment]
this happens because the default for the `vak.util.general.timebin_dur_from_vec` argument `n_decimals_trunc` is 3.

That's the function that `vak.io.spect.to_dataframe` calls to compute the size of the time bin using the timebin_vec from a spectrogram file.

Going to change the default to 5 for now, so it works for you and we can move on.
I don't think this could affect any new user at the moment.

**Comment by yardencsGitHub** [comment]
I just tried to push a change too spect.py to also allow 5 digit timeline_dur in creating the .csv files.. 
It work in my local but I was denied pushing this commit

On Apr 4, 2020, at 10:24 AM, David Nicholson <notifications@github.com> wrote:


this happens because the default for the vak.util.general.timebin_dur_from_vec argument n_decimals_trunc is 3.

That's the function that vak.io.spect.to_dataframe calls to compute the size of the time bin using the timebin_vec from a spectrogram file.

Going to change the default to 5 for now, so it works for you and we can move on.
I don't think this could affect any new user at the moment.

**Comment by NickleDave** [comment]
It was addressed by PR #136 but I realized while fixing issue #134 it's not quite fixed yet

If you run from `master` right now, you will still see the timebin get set to 3 ms, because of the default parameter for `spect.to_dataframe`.

Then it will be fixed, after I merge in that branch
