### ISSUE TITLE
change `val_error_step` and `checkpoint_step` to `val_step` and `ckpt_step`

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/vak#158]
for clarity + brevity

1. step =/= epoch
2. "checkpoint" is too many letters and I'm lazy

**Comment by NickleDave** [comment]
Actually @yardencsGitHub for your sake (and the sake of any models that train on data sets that become giant when we look at every possible time window) we should keep these as "step" and not "epoch"

I still think I will change the logic for when checkpoints get saved as discussed in #159 but this will happen at the level of the `_train` method, not `fit`, so that it depends on what step we're on, not what epoch.

Not trying to make this overly complicated but also don't want to be in a situation where training gets interrupted halfway through and we have nothing to show for those 20 hours except dissipated heat

**Comment by yardencsGitHub** [comment]
I understand it now (I think).
The normal output I see comes from true learning steps.
The ‘rolling’ outputs (those that fill the screen) are coming from a single calculation of the validation set.
I previously set the validation set to be 1000 sec long.
Now it takes a very long time to go through this set (> 1hr just to compute the validation error).
I don’t know why that is the case. It didn’t use to be like that.
Practically it means that I can’t use validation with canaries.



On Apr 12, 2020, at 5:22 PM, David Nicholson <notifications@github.com> wrote:


Closed #158 <https://github.com/NickleDave/vak/issues/158> via 3dbaf96 <https://github.com/NickleDave/vak/commit/3dbaf969c002e87c8f687a344626327d01c11bcf>.

**Comment by NickleDave** [comment]
Working on a fix for this now.

It takes > 1 hr because it's measuring accuracy on every possible window from the validation set.

I think we want it to instead compute metrics the same way we will at test time, by padding spectrograms so that each can be reshaped into a stack of windows, where the "stride" between windows is equal to the size of the window itself.

The current version of the `predict` command basically does this already.
I'm working out how to refactor the code so we can do this more generally.
This will get us most of the way towards having an `eval` command.

**Comment by yardencsGitHub** [comment]
Sounds good.
I assume that the padding is at the end of the file such that it doesn’t create time shifts. 

On Apr 12, 2020, at 8:02 PM, David Nicholson <notifications@github.com> wrote:


Working on a fix for this now.

It takes > 1 hr because it's measuring accuracy on every possible window from the validation set.

I think we want it to instead compute metrics the same way we will at test time, by padding spectrograms so that each can be reshaped into a stack of windows, where the "stride" between windows is equal to the size of the window itself.

The current version of the predict command basically does this already.
I'm working out how to refactor the code so we can do this more generally.
This will get us most of the way towards having an eval command.

**Comment by NickleDave** [comment]
As long as the labeled timebins are padded the same way as the spectrogram and we have a mask to remove padding, it shouldn't matter how we pad, right?
But yes, padding gets added at the "end" currently.

I'd guesstimate I'm about halfway through getting this to work. Will get back to it tonight on the night shift.
