### ISSUE TITLE
current method of converting on/offsets from timebin index to seconds causes misalignment error that increases with duration of file

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#237]
Currently timebin_dur is limited to 4 or 5 decimal positions.
This can lead to 'vak predict' misalignments of ~120 msec if feeding matlab 40sec spectrograms with times bins that differ in the next 2-3 decimal positions.

Is it possible to increase precision by 2-3 more digits?

**Comment by NickleDave** [comment]
@yardencsGitHub per our discussion (off-line), I am changing `lbl_tb2segments` to use the `t` vector from spectrograms for computing onset and offset times

branch in progress here:
https://github.com/NickleDave/vak/tree/change-how-segment-times-are-computed-%23237

I haven't had a chance to test yet but I the idea is mostly there

**Comment by NickleDave** [comment]
@yardencsGitHub I'm attaching the pdf you put in slack demonstrating how error increases with increasing file length because of the current way of converting onsets and offsets from timebin vector indices to seconds

think it might help us figure out a way to write a test for this later
[Need_greater_timebin_dur_accuracy.pdf](https://github.com/NickleDave/vak/files/5003855/Need_greater_timebin_dur_accuracy.pdf)
