### ISSUE TITLE
Predict step crashes due to ValueError: min_segment_dur or majority_vote specified, but 'unlabeled' not in labelmap.

### ISSUE THREAD

**Issue by SamuelBrudner** [NickleDave/vak#241]
While executing "vak predict" to find juvenile song bouts, I can reach the "converting predictions to annotations" step. Then I get the error pasted below. I have no unlabeled silent regions in my dataset. Labels were generated by converting praat annotations to .not.mat files in a way that gives silent/cage noise/calling intervals the label "-". That cause [a resolved issue](https://github.com/NickleDave/vak/issues/239) during training, and may be the source of this error during prediction.

Here's the error:
Traceback (most recent call last):
  File "/home/mooney_lab/anaconda3/envs/VAK/bin/vak", line 11, in <module>
    load_entry_point('vak', 'console_scripts', 'vak')()
  File "/home/mooney_lab/Desktop/vak/src/vak/__main__.py", line 44, in main
    config_file=args.configfile)
  File "/home/mooney_lab/Desktop/vak/src/vak/cli/cli.py", line 28, in cli
    predict(toml_path=config_file)
  File "/home/mooney_lab/Desktop/vak/src/vak/cli/predict.py", line 54, in predict
    logger=logger)
  File "/home/mooney_lab/Desktop/vak/src/vak/core/predict.py", line 217, in predict
    majority_vote=majority_vote)
  File "/home/mooney_lab/Desktop/vak/src/vak/labels.py", line 426, in lbl_tb2segments
    "min_segment_dur or majority_vote specified,"
ValueError: min_segment_dur or majority_vote specified, but 'unlabeled' not in labelmap.
Without 'unlabeled' segments these transforms cannot be applied.

**Comment by NickleDave** [comment]
Hi @SamuelBrudner thank you for reporting this--sorry for not getting back to you sooner.

Unfortunately to apply these cleanups you currently would need to have unlabeled segments.
It's hard to define the "majority" label for a segment, or a minimum duration for a "segment", when the segments are not between two "unlabeled segments" / "silent gaps".

Have you tried running `predict` without them?
You'll need to set
```
majority_vote = false
```
in the `config.toml` file.
If you just leave out `min_segment_dur` then it should default to `None`.

I don't have a good sense of how much you will need this kind of post-hoc processing.

Might help to run without and look at some example outputs.
Please try that and let me know.

If we end up thinking that some sort of post-hoc clean up would help, another option would just be to treat everything that is not song as "unlabeled". I need to think a little bit about what the easiest way for you to do that would be.

**Comment by SamuelBrudner** [comment]
Hi @NickleDave setting majority_vote=false works. At least, I can run through without crashing and generate csv files with annotations. As far as using those CSV files to evaluate vak performance, I have a couple more questions. Two csv files with identical names (dataDirectory_prep_date_time.annot.csv) and non-identical content get created. One is made in the folder from which I run the vak command; the other is in the folder that's given as the value to output_dir in the prep section of my predict.toml file. Can you go over the structure of the data in these csvs? Also, it looks like there might be easy ways to pull data out by making some annotation object in crowsetta (using crowsetta.csv.csv2annot ). Can you go over the structure of that annotation object? I'd really appreciate it. Maybe this issue thread isn't the appropriate place though.

**Comment by SamuelBrudner** [comment]
Also, I probably will try to do post-processing to get rid of unrealistically short bouts and gaps:
![mooneyUbuntu__mooneyUbuntu__-_VNC_Viewer](https://user-images.githubusercontent.com/8064567/88105434-e6137800-cb71-11ea-9b5b-36258ab09df5.png)
![mooneyUbuntu__mooneyUbuntu__-_VNC_Viewer](https://user-images.githubusercontent.com/8064567/88105491-fc213880-cb71-11ea-816f-8478c03817ae.png)

**Comment by SamuelBrudner** [comment]
Much better after some minimum inter-bout silence durations and minimum bout lengths are applied:

![mooneyUbuntu__mooneyUbuntu__-_VNC_Viewer](https://user-images.githubusercontent.com/8064567/88572778-bf3fc080-d00d-11ea-917f-ec58652650f7.png)

**Comment by NickleDave** [comment]
@SamuelBrudner is the segmentation in that last image predicted or is that your training data?
If it's predicted ... looks good! Let me know if I can help more with getting `predict` to work

as far as the two .csv files go:
I think you are referring to the .csv created by `vak prep` and the separate one that gets made by `vak predict`?

I know it's confusing since they are both .csv files but that's just because it's best practice to use a common, conveniently-parsed simple text file format wherever you can; they're different "types" of csvs

The first one (made by `prep`) should not (I hope) have `.annot` at the end. That csv represents the dataset to run predictions on. The same "type" of csv gets made by `vak prep` when you pass it a .toml with a train or learncurve section.

The second one (made by `predict`) contains the actual annotations and has the suffix `.annot.csv`.
You can definitely load this with `crowsetta.csv2annot`.
You are also right that I need to better document what the annotation object is, but at a very high level they have the following attributes:
```
Annotation
  sequence
  audio_file
  annot_file
```
I think `audio_file` is optional, `annot_file` and `sequence` are not.
The `sequence` is what you really want. It has its own attribute `segments`, each of which have `onset_s`, `offset_s` and `label`.

If you want to get all the segments into numpy arrays you can call `Sequence.as_dict` which will return a `dict` that has keys `onsets_s`, `offsets_s`, `labels`

Let me know if that helps. Probably we need to set up a forum for these questions but happy to reply here in the meantime.

**Comment by NickleDave** [comment]
btw I just added some plotting functions in the `vak.plot` sub-module, basically just the stuff that was in that visualization notebook but cleaned-up a little

In case it makes your life any easier.

A quick and dirty example of using them:
```
prep_csv_path = Path(
    '~/Documents/repos/coding/birdsong/tweetynet/results/BFSongRepository/or60yw70/predict/has_notmat_prep_200801_192730.csv'
).expanduser().resolve()
predict_df = pd.read_csv(prep_csv_path)

predict_csv_path =  Path(
    '~/Documents/repos/coding/birdsong/tweetynet/results/BFSongRepository/or60yw70/predict/or60yw70.092712.annot.csv'
).expanduser().resolve()
annots = crowsetta.csv.csv2annot(predict_csv_path)

spect_file = vak.files.spect.load(predict_df.iloc[0, :].spect_path)
s, f, t = spect_file['s'], spect_file['f'], spect_file['t']
annot = annots[0]
imshow_kwargs = dict(vmin=0, vmax=5)
vak.plot.spect_annot(s, t, f, annot, tlim=(8, 25), imshow_kwargs=imshow_kwargs)
```

**Comment by NickleDave** [comment]
going to close this for now but @SamuelBrudner feel free to follow up and if you get a chance let me know how everything's working for you
