### ISSUE TITLE
Allow using the same splits when re-running experiments

### ISSUE THREAD

**Issue by yardencsGitHub** [NickleDave/vak#284]
When re-running learning curve experiments and changing parameters like window sizes or filter sizes we should allow using the same data splits of the original replicates.

Currently, these are saved in the 'results' sub-folders as .csv's that are easy to access and use.

**Comment by NickleDave** [comment]
working on this now

my initial thought was to just make it so that `csv_path` can point either to the csv representing the entire dataset, *or* point to a path from a previous run

but after attempting this I realize I need the original dataset still, e.g. to make sure I have the right timebin duration

better I think to add an optional `previous_run_path` parameter to `core.learncurve`, and a corresponding optional `previous_run_path` option to the LEARNCURVE section of config files. Maintains backward compatibility, more readable
