### ISSUE TITLE
add minimum silent gap option

### ISSUE THREAD

**Issue by alyndanoel** [NickleDave/vak#285]
It might be useful to add a minimum silent gap feature to prevent situations where a very short silent gap is incorrectly added in the middle of a syllable (see attached picture of an example).

![tweetynet_syl_splitting example](https://user-images.githubusercontent.com/48728732/105542375-3efdcd80-5cc7-11eb-861d-8c62d9345e42.png)

**Comment by NickleDave** [comment]
thank you @alyndanoel 

duly noted, will think about how to make it easy to apply this clean-up to predictions

first guess:
- [ ] add parameter `min_silent_dur` to `vak.core.predict` 
- [ ] add corresponding option in `[PREDICT]` section of `config.toml` files

**Comment by NickleDave** [comment]
This was fixed by https://github.com/NickleDave/vak/commit/238c21af074c3a912a93651c5071c537e82bea6e and 7d38d973f273f8fe8cb3fcd2f57da8a63edf503b (I forgot to close 😇 ). Thank you @alyndanoel !

**Comment by NickleDave** [comment]
@all-contributors please add @alyndanoel for ideas

**Comment by NickleDave** [comment]
Replying to myself in 2025, for future reference in case this comes up again: I added a `min_segment_dur` here, but not a `min_silent_interval`.

Here's why:
- for energy-based thresholding, you can have a post-processing parameter like "minimum background segment duration" or "minimum silent gap" or whatever, because you are in a sense doing binary classification where you assign all segments above the threshold to "foreground", and all segments below the threshold to "background". So when you throw away a background segment whose duration is less than the specified `min_silent_dur`, you simply merge the surrounding foreground segments into a single, longer, foreground segment. See for example [`vocalpy.segment.meansquared`](https://vocalpy.readthedocs.io/en/latest/api/generated/vocalpy.segment.meansquared.html) with its `min_silent_dur` argument.
- but with the outputs of a multi-class frame classification model, you can't do this -- you would have to come up with some rule for how to reassign the frames that were in the background class to the foreground classes. One could imagine a more complex scheme, "only drop a background segment and merge if the two surrounding foreground segments have the same class".

This is why we only have two post-processing arguments for multi-class frame labels, as shown in figure 2 of the 2022 paper:

![TweetyNet schematic that shows post-processing transforms](https://iiif.elifesciences.org/lax/63853%2Felife-63853-fig2-v2.tif/full/1500,/0/default.jpg)

This should be in the docs somewhere -- I will raise a separate issue about that.

We should also note that we *could* apply a `min_silent_dur` transform to the output of a *binary* frame classification model, AKA a "voice activity detection" model -- raise an issue for that as well
