### ISSUE TITLE
vak predict crashes when the network predicts 'unlabeled' class for all time bins + applies majority vote transform

### ISSUE THREAD

**Issue by avanikop** [NickleDave/vak#386]
Hi!

I've been using vak for a while now and I ran into an error yesterday. For a few of my folders, vak prep predict.toml works perfectly, but vak predict predict.toml gives the following error:

```python
>Traceback (most recent call last):
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\avani\anaconda3\dir\envs\vak-env\Scripts\vak.exe\__main__.py", line 7, in <module>
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\__main__.py", line 44, in main
    config_file=args.configfile)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\cli\cli.py", line 28, in cli
    predict(toml_path=config_file)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\cli\predict.py", line 54, in predict
    logger=logger)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\core\predict.py", line 204, in predict
    majority_vote=majority_vote)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\labeled_timebins.py", line 383, in lbl_tb2segments
    lbl_tb = majority_vote_transform(lbl_tb, segment_inds_list)
  File "c:\users\avani\anaconda3\dir\envs\vak-env\lib\site-packages\vak\labeled_timebins.py", line 300, in majority_vote_transform
    majority = scipy.stats.mode(segment)[0].item()
ValueError: can only convert an array of size 1 to a Python scalar
```

I have made sure there's no mistake in making the toml files and all my folders have similar data files (.cbin, .rec)
![vak_error_pk92r45](https://user-images.githubusercontent.com/39831515/140889502-b9740272-3d78-4dab-85ea-b3cf46ff1537.PNG)

**Comment by NickleDave** [comment]
Hi @avanikop thank you for raising a detailed issue here -- sorry you're running into this problem

And thank you for double-checking your config but this does look like a real bug we need to fix.

It looks like the code tries to determine which label is most frequent in some segment, to apply the majority vote transform, by calling the `scipy.stats.mode` function  
```
    majority = scipy.stats.mode(segment)[0].item()
```
but for some reason the array returned has more than one value in it:
```
ValueError: can only convert an array of size 1 to a Python scalar
```
I don't see an obvious case where more than one value would be returned by `scipy.stats.mode` -- maybe if there's a `NaN`?
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html

Let me get back to you by email about how to troubleshoot--I think trying to coach you through it on GitHub might not be super efficient--but it's helpful to have it here to track the fix.

**Comment by NickleDave** [comment]
Note to self that this is one place where more info in a traceback would be helpful -- e.g. name of file in dataset, posssibly checkpoint file too?
Trade-off is that if we wrap everything in try-except clauses that fail gracefully to detailed error messages, then it may impact performance

**Comment by NickleDave** [comment]
Making a note here that @avanikop and I met and determined that the issue was a file where the network predicted 'unlabeled' (class 0) for all time bins

This caused "segments" passed to the majority vote transform to be an empty list, which causes the error where the function takes the mode of "nothing", returns an empty array, and then when we call `item()` on that array, there's no value to unpack

The short-term workaround is to train a model with a "noise" class, so that background noises in the file are segmented and recognized as that class. This was done for previous days of data but not in this case, which might explain why the error doesn't always occur.

The long-term solution is to fix all functions in `labeled_timebins` such that they can handle cases where there are no predicted segments for a song. Need to think about the best way to do this and test it.
We definitely need to do this.
@avanikop has kindly agreed to provide data so I can replicate the error and work on such a fix

**Comment by marichard123** [comment]
Hello all! I have encountered the exact same bug when running predict.toml 
I would be also willing to provide data for debugging purposes, as it seems my files also meet the necessary conditions to cause the bug. 
To elaborate, would manually classifying all noise in the audiofile that is not a vocalization as noise serve the purpose of the short-term workaround?

**Comment by NickleDave** [comment]
Hi @marichard123 sorry you're running into this too -- that tells me I need to bump it up the to-do list.

Just to clarify, there are background noises in the file that are segments, which could be labeled?
(like a movement noise or something that triggered the recording)
I.e., it's not a file that's totally "quiet" and literally has just ambient background noise.

If it's the former, then yes, labeling those segments should help.
If it's the latter, then, might not be a workaround.

Please let me know -- I can try to provide further feedback.

I don't think I'll have time to fix this during the week but can start working on it this weekend.

**Comment by marichard123** [comment]
Hello! I do believe there are indeed some movement/scratching noises along with the actual vocalizations.
Would you recommend that I isolate and specifically label these noise occurrences, or should I label everything that's not a vocalization as noise? I'm thinking that these actual noise occurrences are sufficiently spaced out that if I were to only specifically label the brief noise occurrences as opposed to the entire non-vocalization sample, there may still be holes left that would cause the bug. 
Thank you for your help!!

**Comment by NickleDave** [comment]
Can you say more about why you think the bug would still occur? I'm not sure I follow.

If you can provide a traceback and any additional info, that would be helpful.

I'll try to explain what's going on just in case it helps clear anything up:
The true source of the error is that the network predicts the "unlabeled" class for all time bins.
I'll use the term "background" instead of "unlabeled" or "noise", to distinguish ambient background sound from actual noises, such as movement.

`vak` already labels all the non-vocalization time bins for you, by adding the "background" class when it detects there are periods between labeled vocalizations, and assigning the background class to those periods.
Even if you did the same thing yourself, you might still end up with a file where there are no vocalizations, although there might be some actual noises.
Not clear to me if you have a file that's all ambient background noise, or if you have a file with actual noises.
If you haven't labeled those actual non-vocalization noises, then this error is more likely to occur, because the network can only predict the background class.

The workaround is to label any noises if there are enough of them present.
I don't know if that's true for your data, but when recording singly-housed birds in behavioral experiments it's often true.
Those noises often get segmented in the same way that vocalizations are, so you might already have them in the annotation files. It might be easiest to ask Julie if there are non-vocalization sounds that are, or could be, annotated.

If you can label these noises in the training data,  then at least they will get labeled in any files in the prediction dataset  where the same sorts of noises occur. It will prevent the network from predicting all "background".

But even if you go to all that trouble, you might still have a file in your prediction set that is literally all just "background".  
In that case, the workaround won't help you, because the network will (correctly!) label every time bin as "background".

We haven't really run into this before. Test data sets are usually all files with vocalizations, since we want to benchmark on the classes of interest. Obviously that's not true for real world data.

Not obvious to me if another workaround might be just *not* applying the post-processing steps.
Will look at this more as soon as I can.

**Comment by NickleDave** [comment]
@marichard123 sorry for the verbose answer -- just let me know if you're still stuck.
I am working on this bug this weekend. Happy to jump on another Zoom call to try and help troubleshoot

**Comment by NickleDave** [comment]
Update that I ran with the data @avanikop kindly provided but I got a different bug in a different place:
```
Loading checkpoint from:
/home/pimienta/Documents/data/vocal/avani-data/pk92r45_MMAN/vaktrain/results_211108_134532/TweetyNet/checkpoints/max-val-acc-checkpoint.pt 
running predict method of TweetyNet
batch 558 / 559: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 559/559 [01:30<00:00,  6.20it/s]
  0%|                                                                                                                                | 0/559 [00:00<?, ?it/s]converting predictions to annotations
 13%|███████████████▊                                                                                                       | 74/559 [00:01<00:08, 54.85it/s]
Traceback (most recent call last):
  File "/home/pimienta/.cache/pypoetry/virtualenvs/vak-ssZ327oZ-py3.8/bin/vak", line 5, in <module>
    main()
  File "/home/pimienta/Documents/repos/coding/vocal/vak/src/vak/__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "/home/pimienta/Documents/repos/coding/vocal/vak/src/vak/cli/cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "/home/pimienta/Documents/repos/coding/vocal/vak/src/vak/cli/predict.py", line 42, in predict
    core.predict(
  File "/home/pimienta/Documents/repos/coding/vocal/vak/src/vak/core/predict.py", line 261, in predict
    labels, onsets_s, offsets_s = labeled_timebins.lbl_tb2segments(
  File "/home/pimienta/Documents/repos/coding/vocal/vak/src/vak/labeled_timebins.py", line 464, in lbl_tb2segments
    if onsets_s[0] < 0.0:
IndexError: index 0 is out of bounds for axis 0 with size 0
```

This is different from the error involving `mode` above.

I get this error on index 74 which corresponds to `spect_path` `'/home/pimienta/Documents/data/vocal/avani-data/pk92r45_MMAN/190511/spectrograms_generated_211120_224812/pk92r45_190511_081906.4429.cbin.spect.npz'
`.

Note that I generated the `.spect.npz` files myself.

However I think the source of the error is still the same though.
If I do
```
(Pdb) y_pred
array([0, 0, 0, ..., 0, 0, 0])
```
and
```
(Pdb) np.unique(y_pred)
```
I  get
```
array([0])
```
suggesting this is another file where the network suggests all unlabeled bins.

Not sure yet where best to put pre- and post-conditions in functions to catch and handle this, will come back to it tomorrow

**Comment by NickleDave** [comment]
Fix in progress as described in #393 

I see that what's specifically happening with file 74 in the predict dataset is that there are no segments left **after** removing any segments shorter than the minimum segment duration

**Comment by NickleDave** [comment]
Unit tests passed for me locally so this doesn't seem to have broken anything else.
Will wait to see what the CI says.

**Comment by NickleDave** [comment]
@all-contributors please add @avanikop for bug

**Comment by avanikop** [comment]
Hi! I ran into another vak predict bug. The data used in this is the same as before (the folder I shared with David). I'm using vak0.4.0b5.
The output+error traceback was:

> vak predict pk92r45_predict_190511.toml
Logging results to C:\Users\avani\OneDrive\Documents\Veit_lab_data\analysis\pk92r45_MMAN\vak_outputs\predict
loading SpectScaler from path: C:\Users\avani\OneDrive\Documents\Veit_lab_data\analysis\pk92r45_MMAN\vaktrain\results_211124_144946\StandardizeSpect
loading labelmap from path: C:\Users\avani\OneDrive\Documents\Veit_lab_data\analysis\pk92r45_MMAN\vaktrain\results_211124_144946\labelmap.json
loading dataset to predict from csv path: C:\Users\avani\OneDrive\Documents\Veit_lab_data\analysis\pk92r45_MMAN\vak_outputs\predict\190511_prep_211124_160046.csv
will save annotations in .csv file: C:\Users\avani\OneDrive\Documents\Veit_lab_data\analysis\pk92r45_MMAN\vak_outputs\pk92r45_190511.csv
dataset has timebins with duration: 0.002
shape of input to networks used for predictions: torch.Size([1, 152, 88])
instantiating models from model-config map:/n{'TweetyNet': {'optimizer': {'lr': 0.001}, 'network': {}, 'loss': {}, 'metrics': {}}}
loading checkpoint for TweetyNet from path: C:\Users\avani\OneDrive\Documents\Veit_lab_data\analysis\pk92r45_MMAN\vaktrain\results_211124_144946\TweetyNet\checkpoints\max-val-acc-checkpoint.pt
Loading checkpoint from:
C:\Users\avani\OneDrive\Documents\Veit_lab_data\analysis\pk92r45_MMAN\vaktrain\results_211124_144946\TweetyNet\checkpoints\max-val-acc-checkpoint.pt
running predict method of TweetyNet
batch 529 / 530: 100%|████████████████████████████████████████████████████████████| 530/530 [03:41<00:00,  2.39it/s]
  0%|                                                                                       | 0/530 [00:00<?, ?it/s]converting predictions to annotations
 28%|█████████████████████▏                                                       | 146/530 [00:16<00:43,  8.85it/s]
Traceback (most recent call last):
  File "C:\Users\avani\anaconda3\dir\envs\vakenvs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\avani\anaconda3\dir\envs\vakenvs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\avani\anaconda3\dir\envs\vakenvs\Scripts\vak.exe\__main__.py", line 7, in <module>
  File "C:\Users\avani\anaconda3\dir\envs\vakenvs\lib\site-packages\vak\__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "C:\Users\avani\anaconda3\dir\envs\vakenvs\lib\site-packages\vak\cli\cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "C:\Users\avani\anaconda3\dir\envs\vakenvs\lib\site-packages\vak\cli\predict.py", line 58, in predict
    logger=logger,
  File "C:\Users\avani\anaconda3\dir\envs\vakenvs\lib\site-packages\vak\core\predict.py", line 266, in predict
    majority_vote=majority_vote,
  File "C:\Users\avani\anaconda3\dir\envs\vakenvs\lib\site-packages\vak\labeled_timebins.py", line 464, in lbl_tb2segments
    if onsets_s[0] < 0.0:
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by NickleDave** [comment]
Hi @avanikop thank you for the detailed bug report.

Just to check:
are you sure you're using version *0.4.0b5*?

If so, can you please try with the new version I just published to fix this bug, *0.4.0b6*?
The best way to do so might be to create a new environment.
I can't remember if there were any changes you needed to make to install on Mac OS, but it should look something like this:
```
~/repos $ conda create -n vak040b6 python==3.8
~/repos $ conda activate vak040b6
(vak040b6) ~/repos $ conda install torch===1.7.1 torchvision===0.8.2 -c pytorch
(vak040b6) ~/repos $ pip install vak==0.4.0b6
(vak040b6) ~/repos $ pip install tweetynet
```

Either way I can see it's crashing on batch 146 and I will use that info when I write tests for this bugfix, thank you

**Comment by NickleDave** [comment]
tentatively re-opening :(

I have not tested myself again with 0.4.0b6 but I am writing unit tests for `lbl_tb2segments` based on what I see with 0.4.0b5

Still working through the test data but so far I find:
2 songs that are predicted to have only "unlabeled" for all time bins
pk92r45_190511_100932.4800.cbin.spect.npz
pk92r45_190511_081906.4429.cbin.spect.npz

1 song where there are other labels (3s and 7s) but these are removed by the min. segment dur. transform, causing the `lbl_tb` vector to become, again, all "unlabeled"
pk92r45_190511_121855.5322.cbin.spect.npz

:thinking: need to look more at how the two post-processing transforms interact ... I *think* it's the case that the majority vote transform cannot cause everything to become "unlabeled" because it only operates on segments that are defined by not containing the "unlabeled" class

aside: seriously think we should change "unlabeled" to "background" because it sounds weird to say "labeled unlabeled".
This would be by analogy with the "background" class in object detection

**Comment by NickleDave** [comment]
@avanikop and @marichard123 confirmed (thank you!) that the new version seems to be working

so I am keeping this issue closed but will keep working on unit tests
