### ISSUE TITLE
make conda-forge package

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/vak#70]
https://conda-forge.org/docs/maintainer/adding_pkgs.html
https://python-packaging-tutorial.readthedocs.io/en/latest/conda.html

**Comment by NickleDave** [comment]
Created recipe, built succesfully, uploaded to Anaconda cloud.
Added recipe in commit 43ec69c22ee2bdd4765d9126c841bece98dbef60

**Comment by NickleDave** [comment]
Whoops, closed the wrong issue -- this one is for conda-forge

**Comment by bollwyvl** [comment]
Hey, man! Long time no see. I'm happy to help out getting this up on CF, if that's something you're still interested in pursuing. Given the novel deps (crowsetta, etc) you have there are pretty tightly bound to this problem domain, it would probably be reasonable to get them all up in one go. Keeping TF up-to-date is a pretty big job, so you might be hurting a bit there for specific versions, but otherwise seems pretty straightforward.

I also always enjoy some binder-smithing of cool stuff, especially if you've got some sweet audio/visuals to show (sound?) off. Again there, you can't rely on GPU, i don't think.

**Comment by NickleDave** [comment]
@bollwyvl !!! How are you doing?!

Yes I would definitely love to get this and `crowsetta` on conda forge.
I am like literally almost moved to tears that you would offer to help.

I'm sort of in the weeds with this and other things -- could I maybe ping you when we're closer to submitting a paper for this? Guessing near the end of June at the latest. I think my collaborator @yardencsGitHub will kill me if I don't put out other fires with the code first but we definitely want to make it as easy to use as possible once we're there with it

`vak` no longer depends on TF, we switched to PyTorch, not sure if that makes it easier or harder.

And yes definitely want to set up some binder demos too -- I think we could use saved model checkpoints to demo segmenting birdsong syllables in spectrograms without needing a GPU

**Comment by bollwyvl** [comment]
> How are you doing?!

All good, despite all the weirdness out there. Actually doing some plumbing work in the reinforcement learning space, and have been casting about for things that aren't playing atari games or getting sentimental about (figurative) tweets.

>  could I maybe ping you when we're closer to submitting a paper for this?

Sure, whenever!

> vak no longer depends on TF, we switched to PyTorch, not sure if that makes it easier or harder.

Actually harder, from a conda-forge perspective: `pytorch` is hard enough to package that the torch folks run their own conda shop, which doesn't always play well with conda-forge. The best we have from that perspective is a cpu-only build, and like I said, it lags behind some.

Not to be too distracting: the easiest way to dance around it is to have basically everything that _isn't_ PT/TF in `install_requires`, and have an `extras_require` that includes your "good stuff". So you tell your `pip` users to `pip install vak[cpu]` or `vak[gpu]`. Gross, to be sure, but would get over the bar. Make the base at least `vak --version` and `import vak` without that stuff, and it can get over the "what happens in conda-forge stays in conda-forge" bar, while you can happily include in the docs `conda install -c pytorch -c defaults -c conda-forge vak pytorch` and get something that Works For Real. It _might_ even be possible to `run_constrained` packages that _aren't_ even _in_ conda-forge, such that the versions will line up. I would have to investigate.

> want to set up some binder demos

That's actually a much easier place to start, since it could in fact use your upstream library of choice, from wherever you need it, or do `apt-get` stuff, etc. But yeah, no GPU shinies.

> saved model checkpoints

These are actually great candidates for packaging, as we do for [spacy models](https://github.com/conda-forge/spacy-model-en_core_web-feedstock) and a few other things. Seems crazy to be slinging hundred-megabyte files around as packages, but with all the hard-linking that conda (can) does, it's actually pretty efficient, and captures the metadata well.

**Comment by bollwyvl** [comment]
And good luck on the paper!

**Comment by NickleDave** [comment]
hey @bollwyvl any chance I could borrow a few minutes of your time about this?

I can't even get my old recipes to work so I can put up on my own channel 😢 and it is completely not clear to me why
Maybe some evening later this week?

paper is finally up on biorxiv, yay 🎉 
https://www.biorxiv.org/content/10.1101/2020.08.28.272088v1.full.pdf

**Comment by bollwyvl** [comment]
Congrats on the DOI!

Let's hit it some time after Wednesday (pydata triangle talk). Would be
cool to get your stuff into one of the collaboration envs we've been
working in https://github.com/deathbeds/_fam
So you can demo where people can play.

**Comment by NickleDave** [comment]
thank you
better a DOI than DOA as Tom Waits never used to say

!
Hope the talk goes well
Thursday or Friday after 5 works for me, or even the weekend if by any chance you're free.

and yes! would love to demo
although Tony might be very sick of hearing me talk about songbirds at this point
I'll segment some bat calls just to change it up

**Comment by NickleDave** [comment]
Hey @bollwyvl just pinging you again -- hope the talk went well.
Please let me if there's a time early next week we could meet

**Comment by NickleDave** [comment]
Fixed by https://github.com/conda-forge/staged-recipes/pull/17426#issuecomment-1007710541

Thank you again @bollwyvl for introducing me to `grayskull` and helping me figure out what I needed to fix about dependencies

**Comment by bollwyvl** [comment]
😎 Congrats! And feel free to @ me if you ever run into trouble.

**Comment by NickleDave** [comment]
🙏 thank you
